# Generated by Django 5.1.5 on 2026-01-24 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessControl', '0002_permission_rename_name_role_role_name_rolepermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role_name',
            new_name='name',
        ),
    ]
