# Generated by Django 5.1.5 on 2026-01-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessControl', '0003_rename_role_name_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='accessControl.permission'),
        ),
    ]
